-- MySQL Script generated by MySQL Workbench
-- Tue Feb 24 18:53:39 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Museum
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Museum
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Museum` DEFAULT CHARACTER SET utf8 ;
USE `Museum` ;

-- -----------------------------------------------------
-- Table `Museum`.`Artifact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Museum`.`Artifact` ;

CREATE TABLE IF NOT EXISTS `Museum`.`Artifact` (
  `artifact_id` INT NOT NULL,
  `name` VARCHAR(100) NULL,
  `description` VARCHAR(255) NULL,
  `origin` VARCHAR(100) NULL,
  `historical_period` VARCHAR(100) NULL,
  `acquisition_date` DATE NULL,
  PRIMARY KEY (`artifact_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Museum`.`Exhibition`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Museum`.`Exhibition` ;

CREATE TABLE IF NOT EXISTS `Museum`.`Exhibition` (
  `exhibition_id` INT NOT NULL,
  `name` VARCHAR(100) NULL,
  `start_date` DATE NULL,
  `end_date` DATE NULL,
  PRIMARY KEY (`exhibition_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Museum`.`Staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Museum`.`Staff` ;

CREATE TABLE IF NOT EXISTS `Museum`.`Staff` (
  `staff_id` INT NOT NULL,
  `first_name` VARCHAR(50) NULL,
  `last_name` VARCHAR(50) NULL,
  `position` VARCHAR(100) NULL,
  `phone` VARCHAR(20) NULL,
  `email` VARCHAR(100) NULL,
  PRIMARY KEY (`staff_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Museum`.`Visitor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Museum`.`Visitor` ;

CREATE TABLE IF NOT EXISTS `Museum`.`Visitor` (
  `visitor_id` INT NOT NULL,
  `first_name` VARCHAR(50) NULL,
  `last_name` VARCHAR(50) NULL,
  `email` VARCHAR(100) NULL,
  `phone` VARCHAR(20) NULL,
  PRIMARY KEY (`visitor_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Museum`.`Ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Museum`.`Ticket` ;

CREATE TABLE IF NOT EXISTS `Museum`.`Ticket` (
  `ticket_id` INT NOT NULL,
  `puchase_date` DATE NULL,
  `ticket_type` VARCHAR(50) NULL,
  `price` DECIMAL(8,2) NULL,
  `visitor_id` INT NOT NULL,
  PRIMARY KEY (`ticket_id`, `visitor_id`),
  INDEX `fk_ticket_visitor_idx` (`visitor_id` ASC) VISIBLE,
  CONSTRAINT `fk_ticket_visitor`
    FOREIGN KEY (`visitor_id`)
    REFERENCES `Museum`.`Visitor` (`visitor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Museum`.`Exhibition_Artifact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Museum`.`Exhibition_Artifact` ;

CREATE TABLE IF NOT EXISTS `Museum`.`Exhibition_Artifact` (
  `exhibition_id` INT NOT NULL,
  `artifact_id` INT NOT NULL,
  PRIMARY KEY (`exhibition_id`, `artifact_id`),
  INDEX `fk_exhibitartifact_artifact_idx` (`artifact_id` ASC) VISIBLE,
  CONSTRAINT `fk_exhibitartifact_exhibition`
    FOREIGN KEY (`exhibition_id`)
    REFERENCES `Museum`.`Exhibition` (`exhibition_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exhibitartifact_artifact`
    FOREIGN KEY (`artifact_id`)
    REFERENCES `Museum`.`Artifact` (`artifact_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
